ALL: demo1 demo2 demo3 demo4

demo1:
	gcc -odemo1 demo1.c -I../include -noixemul

demo2:
	gcc -odemo2 demo2.c -I../include -noixemul

demo3:
	gcc -odemo3 demo3.c -I../include -noixemul

demo4:
	gcc -odemo4 demo4.c -I../include -noixemul

